(async () => {
  try {
    console.log("running...")
  } catch (e) {
    console.error(e)
  }
})()
